# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 5.0.1
_src_path: gh:epics-containers/deployment-template-argocd
argocd_cluster: argus
argocd_server: argocd.diamond.ac.uk
cluster_name: p49
cluster_namespace: p49-beamline
deployment_repo: https://github.com/epics-containers/p49-deployment
description: p49 IOC Instances and Services
domain: p49
git_platform: github.com
github_org: epics-containers
logging_url: https://graylog2.diamond.ac.uk/search?rangetype=relative&fields=message%2Csource&width=1489&highlightMessage=&relative=172800&q=pod_name%3A{service_name}*
services_release: 2024.9.1
services_repo: https://github.com/epics-containers/p49-services
